// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driver.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecoverTaskRequest struct {
	TaskId               string      `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Handle               *TaskHandle `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RecoverTaskRequest) Reset()         { *m = RecoverTaskRequest{} }
func (m *RecoverTaskRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverTaskRequest) ProtoMessage()    {}
func (*RecoverTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{0}
}
func (m *RecoverTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverTaskRequest.Unmarshal(m, b)
}
func (m *RecoverTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverTaskRequest.Marshal(b, m, deterministic)
}
func (dst *RecoverTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverTaskRequest.Merge(dst, src)
}
func (m *RecoverTaskRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverTaskRequest.Size(m)
}
func (m *RecoverTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverTaskRequest proto.InternalMessageInfo

func (m *RecoverTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *RecoverTaskRequest) GetHandle() *TaskHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

type StartTaskRequest struct {
	Task                 *TaskConfig `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StartTaskRequest) Reset()         { *m = StartTaskRequest{} }
func (m *StartTaskRequest) String() string { return proto.CompactTextString(m) }
func (*StartTaskRequest) ProtoMessage()    {}
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{1}
}
func (m *StartTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskRequest.Unmarshal(m, b)
}
func (m *StartTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskRequest.Marshal(b, m, deterministic)
}
func (dst *StartTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskRequest.Merge(dst, src)
}
func (m *StartTaskRequest) XXX_Size() int {
	return xxx_messageInfo_StartTaskRequest.Size(m)
}
func (m *StartTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskRequest proto.InternalMessageInfo

func (m *StartTaskRequest) GetTask() *TaskConfig {
	if m != nil {
		return m.Task
	}
	return nil
}

type TaskConfig struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 string            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	MsgpackDriverConfig  []byte            `protobuf:"bytes,3,opt,name=msgpack_driver_config,json=msgpackDriverConfig,proto3" json:"msgpack_driver_config,omitempty"`
	Env                  map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources            *Resources        `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Mounts               []*Mount          `protobuf:"bytes,6,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Devices              []*Device         `protobuf:"bytes,7,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TaskConfig) Reset()         { *m = TaskConfig{} }
func (m *TaskConfig) String() string { return proto.CompactTextString(m) }
func (*TaskConfig) ProtoMessage()    {}
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{2}
}
func (m *TaskConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskConfig.Unmarshal(m, b)
}
func (m *TaskConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskConfig.Marshal(b, m, deterministic)
}
func (dst *TaskConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskConfig.Merge(dst, src)
}
func (m *TaskConfig) XXX_Size() int {
	return xxx_messageInfo_TaskConfig.Size(m)
}
func (m *TaskConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TaskConfig proto.InternalMessageInfo

func (m *TaskConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskConfig) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *TaskConfig) GetMsgpackDriverConfig() []byte {
	if m != nil {
		return m.MsgpackDriverConfig
	}
	return nil
}

func (m *TaskConfig) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *TaskConfig) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *TaskConfig) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *TaskConfig) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Resources struct {
	// CPU CFS (Completely Fair Scheduler) period. Default: 0 (not specified).
	CpuPeriod int64 `protobuf:"varint,1,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	// CPU CFS (Completely Fair Scheduler) quota. Default: 0 (not specified).
	CpuQuota int64 `protobuf:"varint,2,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	// CPU shares (relative weight vs. other containers). Default: 0 (not specified).
	CpuShares int64 `protobuf:"varint,3,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	// Memory limit in bytes. Default: 0 (not specified).
	MemoryLimitInBytes int64 `protobuf:"varint,4,opt,name=memory_limit_in_bytes,json=memoryLimitInBytes,proto3" json:"memory_limit_in_bytes,omitempty"`
	// OOMScoreAdj adjusts the oom-killer score. Default: 0 (not specified).
	OomScoreAdj int64 `protobuf:"varint,5,opt,name=oom_score_adj,json=oomScoreAdj,proto3" json:"oom_score_adj,omitempty"`
	// CpusetCpus constrains the allowed set of logical CPUs. Default: "" (not specified).
	CpusetCpus string `protobuf:"bytes,6,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	// CpusetMems constrains the allowed set of memory nodes. Default: "" (not specified).
	CpusetMems           string   `protobuf:"bytes,7,opt,name=cpuset_mems,json=cpusetMems,proto3" json:"cpuset_mems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{3}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetCpuPeriod() int64 {
	if m != nil {
		return m.CpuPeriod
	}
	return 0
}

func (m *Resources) GetCpuQuota() int64 {
	if m != nil {
		return m.CpuQuota
	}
	return 0
}

func (m *Resources) GetCpuShares() int64 {
	if m != nil {
		return m.CpuShares
	}
	return 0
}

func (m *Resources) GetMemoryLimitInBytes() int64 {
	if m != nil {
		return m.MemoryLimitInBytes
	}
	return 0
}

func (m *Resources) GetOomScoreAdj() int64 {
	if m != nil {
		return m.OomScoreAdj
	}
	return 0
}

func (m *Resources) GetCpusetCpus() string {
	if m != nil {
		return m.CpusetCpus
	}
	return ""
}

func (m *Resources) GetCpusetMems() string {
	if m != nil {
		return m.CpusetMems
	}
	return ""
}

type Mount struct {
	TaskPath             string   `protobuf:"bytes,1,opt,name=task_path,json=taskPath,proto3" json:"task_path,omitempty"`
	HostPath             string   `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	Readonly             bool     `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{4}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetTaskPath() string {
	if m != nil {
		return m.TaskPath
	}
	return ""
}

func (m *Mount) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *Mount) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type Device struct {
	TaskPath             string   `protobuf:"bytes,1,opt,name=task_path,json=taskPath,proto3" json:"task_path,omitempty"`
	HostPath             string   `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	Permissions          string   `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{5}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetTaskPath() string {
	if m != nil {
		return m.TaskPath
	}
	return ""
}

func (m *Device) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *Device) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

type StartTaskResponse struct {
	Handle               *TaskHandle `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StartTaskResponse) Reset()         { *m = StartTaskResponse{} }
func (m *StartTaskResponse) String() string { return proto.CompactTextString(m) }
func (*StartTaskResponse) ProtoMessage()    {}
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{6}
}
func (m *StartTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskResponse.Unmarshal(m, b)
}
func (m *StartTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskResponse.Marshal(b, m, deterministic)
}
func (dst *StartTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskResponse.Merge(dst, src)
}
func (m *StartTaskResponse) XXX_Size() int {
	return xxx_messageInfo_StartTaskResponse.Size(m)
}
func (m *StartTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskResponse proto.InternalMessageInfo

func (m *StartTaskResponse) GetHandle() *TaskHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

type TaskHandle struct {
	Driver               string      `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Config               *TaskConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	State                string      `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	MsgpackDriverState   []byte      `protobuf:"bytes,4,opt,name=msgpack_driver_state,json=msgpackDriverState,proto3" json:"msgpack_driver_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskHandle) Reset()         { *m = TaskHandle{} }
func (m *TaskHandle) String() string { return proto.CompactTextString(m) }
func (*TaskHandle) ProtoMessage()    {}
func (*TaskHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_10e4c8d04768fe57, []int{7}
}
func (m *TaskHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskHandle.Unmarshal(m, b)
}
func (m *TaskHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskHandle.Marshal(b, m, deterministic)
}
func (dst *TaskHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskHandle.Merge(dst, src)
}
func (m *TaskHandle) XXX_Size() int {
	return xxx_messageInfo_TaskHandle.Size(m)
}
func (m *TaskHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskHandle.DiscardUnknown(m)
}

var xxx_messageInfo_TaskHandle proto.InternalMessageInfo

func (m *TaskHandle) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *TaskHandle) GetConfig() *TaskConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *TaskHandle) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *TaskHandle) GetMsgpackDriverState() []byte {
	if m != nil {
		return m.MsgpackDriverState
	}
	return nil
}

func init() {
	proto.RegisterType((*RecoverTaskRequest)(nil), "hashicorp.nomad.plugins.drivers.base.proto.RecoverTaskRequest")
	proto.RegisterType((*StartTaskRequest)(nil), "hashicorp.nomad.plugins.drivers.base.proto.StartTaskRequest")
	proto.RegisterType((*TaskConfig)(nil), "hashicorp.nomad.plugins.drivers.base.proto.TaskConfig")
	proto.RegisterMapType((map[string]string)(nil), "hashicorp.nomad.plugins.drivers.base.proto.TaskConfig.EnvEntry")
	proto.RegisterType((*Resources)(nil), "hashicorp.nomad.plugins.drivers.base.proto.Resources")
	proto.RegisterType((*Mount)(nil), "hashicorp.nomad.plugins.drivers.base.proto.Mount")
	proto.RegisterType((*Device)(nil), "hashicorp.nomad.plugins.drivers.base.proto.Device")
	proto.RegisterType((*StartTaskResponse)(nil), "hashicorp.nomad.plugins.drivers.base.proto.StartTaskResponse")
	proto.RegisterType((*TaskHandle)(nil), "hashicorp.nomad.plugins.drivers.base.proto.TaskHandle")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriverClient interface {
	RecoverTask(ctx context.Context, in *RecoverTaskRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) RecoverTask(ctx context.Context, in *RecoverTaskRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.base.proto.Driver/RecoverTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, "/hashicorp.nomad.plugins.drivers.base.proto.Driver/StartTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
type DriverServer interface {
	RecoverTask(context.Context, *RecoverTaskRequest) (*empty.Empty, error)
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_RecoverTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).RecoverTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.base.proto.Driver/RecoverTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).RecoverTask(ctx, req.(*RecoverTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashicorp.nomad.plugins.drivers.base.proto.Driver/StartTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.nomad.plugins.drivers.base.proto.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecoverTask",
			Handler:    _Driver_RecoverTask_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _Driver_StartTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}

func init() { proto.RegisterFile("driver.proto", fileDescriptor_driver_10e4c8d04768fe57) }

var fileDescriptor_driver_10e4c8d04768fe57 = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xe3, 0xc4, 0x49, 0x26, 0xfd, 0x3e, 0x95, 0xa5, 0x2d, 0x56, 0x2a, 0x44, 0xe4, 0xab,
	0x88, 0x0b, 0x97, 0x06, 0x51, 0x21, 0xc4, 0x8f, 0xe8, 0x8f, 0x44, 0x51, 0x8b, 0xda, 0x0d, 0x57,
	0x48, 0x60, 0x6d, 0xed, 0x6d, 0xe2, 0x26, 0xf6, 0x6e, 0x77, 0xd7, 0x91, 0x72, 0xc1, 0x0b, 0xf0,
	0x4c, 0xbc, 0x0a, 0xaf, 0x02, 0x68, 0x77, 0x9d, 0x34, 0xf4, 0x8a, 0xb4, 0x5c, 0xd9, 0x33, 0x67,
	0xe6, 0xcc, 0xce, 0x8c, 0x7d, 0x16, 0x56, 0x13, 0x91, 0x4e, 0xa8, 0x08, 0xb9, 0x60, 0x8a, 0xa1,
	0xc7, 0x43, 0x22, 0x87, 0x69, 0xcc, 0x04, 0x0f, 0x73, 0x96, 0x91, 0x24, 0xe4, 0xe3, 0x62, 0x90,
	0xe6, 0x32, 0xb4, 0x51, 0x32, 0x3c, 0x27, 0x92, 0xda, 0xd8, 0xf6, 0xd6, 0x80, 0xb1, 0xc1, 0x98,
	0x6e, 0x1b, 0xeb, 0xbc, 0xb8, 0xd8, 0xa6, 0x19, 0x57, 0x53, 0x0b, 0x06, 0x5f, 0x01, 0x61, 0x1a,
	0xb3, 0x09, 0x15, 0x1f, 0x89, 0x1c, 0x61, 0x7a, 0x55, 0x50, 0xa9, 0xd0, 0x03, 0xa8, 0x2b, 0x22,
	0x47, 0x51, 0x9a, 0xf8, 0x4e, 0xc7, 0xe9, 0x36, 0xb1, 0xa7, 0xcd, 0xa3, 0x04, 0x7d, 0x00, 0x6f,
	0x48, 0xf2, 0x64, 0x4c, 0xfd, 0x4a, 0xc7, 0xe9, 0xb6, 0x7a, 0xbb, 0xe1, 0xdf, 0x1f, 0x24, 0xd4,
	0x15, 0xde, 0x99, 0x6c, 0x5c, 0xb2, 0x04, 0x5f, 0x60, 0xad, 0xaf, 0x88, 0x50, 0x8b, 0xc5, 0xdf,
	0x43, 0x55, 0x57, 0x33, 0x95, 0x6f, 0x51, 0x61, 0x9f, 0xe5, 0x17, 0xe9, 0x00, 0x1b, 0x8e, 0xe0,
	0x87, 0x0b, 0x70, 0xed, 0x44, 0xff, 0x43, 0x65, 0xde, 0x52, 0x25, 0x4d, 0x10, 0x82, 0x6a, 0x21,
	0xa9, 0x30, 0xcd, 0x34, 0xb1, 0x79, 0x47, 0x3d, 0xd8, 0xc8, 0xe4, 0x80, 0x93, 0x78, 0x14, 0xd9,
	0x0a, 0x51, 0x6c, 0x92, 0x7d, 0xb7, 0xe3, 0x74, 0x57, 0xf1, 0xfd, 0x12, 0x3c, 0x30, 0x58, 0xc9,
	0x7b, 0x06, 0x2e, 0xcd, 0x27, 0x7e, 0xb5, 0xe3, 0x76, 0x5b, 0xbd, 0x37, 0xb7, 0x3b, 0x71, 0x78,
	0x98, 0x4f, 0x0e, 0x73, 0x25, 0xa6, 0x58, 0x73, 0xa1, 0x3e, 0x34, 0x05, 0x95, 0xac, 0x10, 0x31,
	0x95, 0x7e, 0xcd, 0x8c, 0xe2, 0xd9, 0x32, 0xc4, 0x78, 0x96, 0x8c, 0xaf, 0x79, 0xd0, 0x11, 0x78,
	0x19, 0x2b, 0x72, 0x25, 0x7d, 0xcf, 0x1c, 0x75, 0x67, 0x19, 0xc6, 0x13, 0x9d, 0x89, 0x4b, 0x02,
	0x74, 0x0c, 0xf5, 0x84, 0x4e, 0x52, 0x7d, 0xba, 0xba, 0xe1, 0xea, 0x2d, 0xc3, 0x75, 0x60, 0x52,
	0xf1, 0x8c, 0xa2, 0xbd, 0x0b, 0x8d, 0x59, 0xfb, 0x68, 0x0d, 0xdc, 0x11, 0x9d, 0x96, 0x5b, 0xd2,
	0xaf, 0x68, 0x1d, 0x6a, 0x13, 0x32, 0x2e, 0x68, 0xb9, 0x27, 0x6b, 0xbc, 0xa8, 0x3c, 0x77, 0x82,
	0x5f, 0x0e, 0x34, 0xe7, 0x9d, 0xa2, 0x87, 0x00, 0x31, 0x2f, 0x22, 0x4e, 0x45, 0xca, 0xec, 0x9a,
	0x5d, 0xdc, 0x8c, 0x79, 0x71, 0x6a, 0x1c, 0x68, 0x0b, 0xb4, 0x11, 0x5d, 0x15, 0x4c, 0x11, 0x43,
	0xe5, 0xe2, 0x46, 0xcc, 0x8b, 0x33, 0x6d, 0xcf, 0x72, 0xe5, 0x90, 0x08, 0x2a, 0xcd, 0xae, 0x6d,
	0x6e, 0xdf, 0x38, 0xd0, 0x0e, 0x6c, 0x64, 0x34, 0x63, 0x62, 0x1a, 0x8d, 0xd3, 0x2c, 0x55, 0x51,
	0x9a, 0x47, 0xe7, 0x53, 0x45, 0xa5, 0x5f, 0x35, 0x91, 0xc8, 0x82, 0xc7, 0x1a, 0x3b, 0xca, 0xf7,
	0x34, 0x82, 0x02, 0xf8, 0x8f, 0xb1, 0x2c, 0x92, 0x31, 0x13, 0x34, 0x22, 0xc9, 0xa5, 0xd9, 0xa2,
	0x8b, 0x5b, 0x8c, 0x65, 0x7d, 0xed, 0x7b, 0x9b, 0x5c, 0xa2, 0x47, 0xd0, 0x8a, 0x79, 0x21, 0xa9,
	0x8a, 0xf4, 0xc3, 0xf7, 0x4c, 0x7f, 0x60, 0x5d, 0xfb, 0xbc, 0x90, 0x0b, 0x01, 0x19, 0xcd, 0xf4,
	0xa8, 0x17, 0x02, 0x4e, 0x68, 0x26, 0x83, 0xcf, 0x50, 0x33, 0x8b, 0xd1, 0xdd, 0x99, 0x7f, 0x96,
	0x13, 0x35, 0x2c, 0x87, 0xd7, 0xd0, 0x8e, 0x53, 0xa2, 0x86, 0x1a, 0x1c, 0x32, 0xa9, 0x2c, 0x68,
	0xa7, 0xd8, 0xd0, 0x0e, 0x03, 0xb6, 0xa1, 0x21, 0x28, 0x49, 0x58, 0x3e, 0x9e, 0x9a, 0xc6, 0x1b,
	0x78, 0x6e, 0x07, 0x09, 0x78, 0x76, 0x57, 0x77, 0xe0, 0xef, 0x40, 0x8b, 0x53, 0x91, 0xa5, 0x52,
	0xa6, 0x2c, 0xb7, 0xb3, 0x6d, 0xe2, 0x45, 0x57, 0x10, 0xc3, 0xbd, 0x05, 0x19, 0x90, 0x9c, 0xe5,
	0x92, 0x2e, 0x68, 0x8d, 0xf3, 0x4f, 0xb4, 0xe6, 0xbb, 0x63, 0xb5, 0xc0, 0xba, 0xd1, 0x26, 0x78,
	0x36, 0x6f, 0x26, 0x71, 0xd6, 0xd2, 0x65, 0xcb, 0x1f, 0xbe, 0x72, 0x27, 0x01, 0x2a, 0x59, 0xf4,
	0xc7, 0x2b, 0x15, 0x51, 0xb4, 0xec, 0xdb, 0x1a, 0xe8, 0x09, 0xac, 0xdf, 0x50, 0x19, 0x1b, 0x54,
	0x35, 0x22, 0x83, 0xfe, 0x10, 0x99, 0xbe, 0x46, 0x7a, 0x3f, 0x1d, 0xf0, 0xac, 0x8d, 0x06, 0xd0,
	0x5a, 0x10, 0x6d, 0xf4, 0x7a, 0x39, 0x5d, 0xb8, 0xa9, 0xf6, 0xed, 0xcd, 0xd0, 0xde, 0x10, 0xe1,
	0xec, 0x86, 0x08, 0x0f, 0xf5, 0x0d, 0x11, 0xac, 0xa0, 0x6f, 0x0e, 0x34, 0xe7, 0x8b, 0x41, 0x2f,
	0x97, 0xa9, 0x73, 0x53, 0xd6, 0xdb, 0xaf, 0x6e, 0x99, 0x6d, 0xbf, 0x86, 0x60, 0x65, 0xaf, 0xfe,
	0xa9, 0x66, 0x0f, 0xe8, 0x99, 0xc7, 0xd3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x36, 0x69,
	0xd3, 0x13, 0x07, 0x00, 0x00,
}
